# Лабораторная работа №1
## Выполнил студент группы ГРУППА ФИО

 БФИ 2302 Мазембе Нгунги Маршелл

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [ ]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [ ]:
import random
import time

In [ ]:
user_m = input()
user_n = input()
user_min_limit = input()
user_max_limit = input()
user_m, user_n, user_min_limit, user_max_limit

4
4
5
6


('4', '4', '5', '6')

In [ ]:
import numpy as np

def generate_random_matrix(m=3, n=3, min_limit=0, max_limit=10):
    return np.random.randint(min_limit, max_limit + 1, size=(m, n))

# Exemplo de uso:
matriz_exemplo = generate_random_matrix(4, 5, 1, 20)
print(matriz_exemplo)

[[14  2  8  4 19]
 [ 6  6 19  5 18]
 [12 14  2  9  3]
 [ 6  1  7  4  1]]


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [ ]:
import copy

In [ ]:
# Сортировка выбором.
# Берётся срез массива, в котором минимальный элемент переносят в самый левый угол,
# после чего срез уменьшается и цикл повторяется.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

--- 0 ms ---


In [ ]:
# Сортировка вставкой.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

--- 0 ms ---


In [ ]:
# Сортировка обменом. || Сортировка пузырьком.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

--- 0 ms ---


In [ ]:
# Сортировка Шелла.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

--- 0 ms ---


In [ ]:
# Быстрая сортировка.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))


--- 1 ms ---


In [ ]:
# Турнирная сортировка.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

NameError: ignored

In [ ]:
import numpy as np
import time
import copy

# Função para gerar uma matriz aleatória
def generate_random_matrix(m=3, n=3, min_limit=0, max_limit=10):
    return np.random.randint(min_limit, max_limit + 1, size=(m, n))

# Inputs do usuário para definir a matriz
user_m = int(input("Número de linhas (m): "))
user_n = int(input("Número de colunas (n): "))
user_min_limit = int(input("Valor mínimo: "))
user_max_limit = int(input("Valor máximo: "))

# Gerar a matriz baseada nos inputs do usuário
matrix = generate_random_matrix(user_m, user_n, user_min_limit, user_max_limit)
print("Matriz original:")
print(matrix)

# Função de Selection Sort
def selection_sort(matrix):
    sorted_matrix = copy.deepcopy(matrix)
    for row in sorted_matrix:
        for i in range(len(row)):
            min_idx = i
            for j in range(i + 1, len(row)):
                if row[j] < row[min_idx]:
                    min_idx = j
            row[i], row[min_idx] = row[min_idx], row[i]
    return sorted_matrix

# Função de Insertion Sort
def insertion_sort(matrix):
    sorted_matrix = copy.deepcopy(matrix)
    for row in sorted_matrix:
        for i in range(1, len(row)):
            key = row[i]
            j = i - 1
            while j >= 0 and row[j] > key:
                row[j + 1] = row[j]
                j -= 1
            row[j + 1] = key
    return sorted_matrix

# Função de Bubble Sort
def bubble_sort(matrix):
    sorted_matrix = copy.deepcopy(matrix)
    for row in sorted_matrix:
        n = len(row)
        for i in range(n):
            for j in range(0, n - i - 1):
                if row[j] > row[j + 1]:
                    row[j], row[j + 1] = row[j + 1], row[j]
    return sorted_matrix

# Função de Shell Sort
def shell_sort(matrix):
    sorted_matrix = copy.deepcopy(matrix)
    for row in sorted_matrix:
        gap = len(row) // 2
        while gap > 0:
            for i in range(gap, len(row)):
                temp = row[i]
                j = i
                while j >= gap and row[j - gap] > temp:
                    row[j] = row[j - gap]
                    j -= gap
                row[j] = temp
            gap //= 2
    return sorted_matrix

# Função de Quick Sort
def quick_sort(matrix):
    def quicksort_helper(arr):
        if len(arr) <= 1:
            return arr
        pivot = arr[len(arr) // 2]
        left = [x for x in arr if x < pivot]
        middle = [x for x in arr if x == pivot]
        right = [x for x in arr if x > pivot]
        return quicksort_helper(left) + middle + quicksort_helper(right)

    sorted_matrix = copy.deepcopy(matrix)
    for i in range(len(sorted_matrix)):
        sorted_matrix[i] = quicksort_helper(sorted_matrix[i])
    return sorted_matrix

# Função de Heap Sort (Torneio)
import heapq
def heap_sort(matrix):
    sorted_matrix = copy.deepcopy(matrix)
    for i in range(len(sorted_matrix)):
        heapq.heapify(sorted_matrix[i])
        sorted_matrix[i] = [heapq.heappop(sorted_matrix[i]) for _ in range(len(sorted_matrix[i]))]
    return sorted_matrix

# Função para ordenação padrão do NumPy
def numpy_sort(matrix):
    return np.sort(matrix, axis=1)

# Teste e medição de tempo para cada algoritmo
algorithms = {
    "Selection Sort": selection_sort,
    "Insertion Sort": insertion_sort,
    "Bubble Sort": bubble_sort,
    "Shell Sort": shell_sort,
    "Quick Sort": quick_sort,
    "Heap Sort": heap_sort,
    "NumPy Sort": numpy_sort
}

# Dicionário para armazenar os tempos de execução
execution_times = {}

print("\nResultados das Ordenações:")
for name, sort_function in algorithms.items():
    start_time = time.time()
    sorted_matrix = sort_function(matrix)
    execution_time = time.time() - start_time
    execution_times[name] = execution_time

    print(f"\n{name}:")
    print(sorted_matrix)
    print(f"Tempo: {execution_time:.6f} segundos")

# Comparação de tempos
print("\n--- Comparação de Tempo de Execução ---")
for name, exec_time in execution_times.items():
    print(f"{name}: {exec_time:.6f} segundos")

Número de linhas (m): 4
Número de colunas (n): 5
Valor mínimo: 4
Valor máximo: 8
Matriz original:
[[5 8 8 8 5]
 [7 5 4 5 8]
 [5 4 8 5 6]
 [6 8 7 6 6]]

Resultados das Ordenações:

Selection Sort:
[[5 5 8 8 8]
 [4 5 5 7 8]
 [4 5 5 6 8]
 [6 6 6 7 8]]
Tempo: 0.000905 segundos

Insertion Sort:
[[5 5 8 8 8]
 [4 5 5 7 8]
 [4 5 5 6 8]
 [6 6 6 7 8]]
Tempo: 0.000082 segundos

Bubble Sort:
[[5 5 8 8 8]
 [4 5 5 7 8]
 [4 5 5 6 8]
 [6 6 6 7 8]]
Tempo: 0.000077 segundos

Shell Sort:
[[5 5 8 8 8]
 [4 5 5 7 8]
 [4 5 5 6 8]
 [6 6 6 7 8]]
Tempo: 0.000077 segundos

Quick Sort:
[[5 5 8 8 8]
 [4 5 5 7 8]
 [4 5 5 6 8]
 [6 6 6 7 8]]
Tempo: 0.000106 segundos


TypeError: heapify() argument must be list, not numpy.ndarray

### Вывод
